server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    properties:
      schema.registry.url: http://localhost:8081
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
      spring.json.add.type.headers: false